
@public
def foo() -> num:
    return block.fail
